# Generated by Django 4.2.24 on 2025-09-28 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('phishing_click', 'Phishing Link Clicked'), ('simulation_view', 'Educational Page Viewed'), ('admin_login', 'Admin Login'), ('campaign_created', 'Campaign Created')], max_length=50)),
                ('user_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='analytics_s_timesta_67f2c9_idx'), models.Index(fields=['event_type'], name='analytics_s_event_t_23d6f8_idx')],
            },
        ),
    ]
