# Generated by Django 4.2.24 on 2025-09-28 21:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('phishing', 'Phishing'), ('educational', 'Educational')], max_length=50)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('variables', models.JSONField(default=dict, help_text='Available template variables')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='phishingtemplate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='phishingtemplate',
            name='category',
            field=models.CharField(choices=[('urgent', 'Urgent Action Required'), ('security', 'Security Alert'), ('update', 'System Update'), ('social', 'Social Engineering'), ('custom', 'Custom Template')], default='security', max_length=50),
        ),
        migrations.AddField(
            model_name='phishingtemplate',
            name='difficulty_level',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=2),
        ),
        migrations.AddField(
            model_name='phishingtemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='phishingtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='simulationevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulationevent',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulations.phishingtemplate'),
        ),
        migrations.AddField(
            model_name='targetuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='simulationevent',
            index=models.Index(fields=['unique_simulation_id'], name='simulations_unique__55e21f_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationevent',
            index=models.Index(fields=['clicked_link'], name='simulations_clicked_a24ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationevent',
            index=models.Index(fields=['created_at'], name='simulations_created_195072_idx'),
        ),
    ]
